my_project:
  settings:
    - __init__.py
    - dev.py
    - prod.py
  mainapp:
    - __init__.py1
    - models.py1
    - views.py1
    - templates:
        - mainapp:
            - base.html
            - index.html
  authapp:
    - __init__.py2
    - models.py2
    - views.py2  
    - templates:
        - authapp:
            - base.html
            - index.html
